worker_processes  1;

events {
    worker_connections  1024;
}

http {

resolver 127.0.0.11 valid=30s ipv6=off;

log_format cors '"$http_referer" $remote_addr "$request" $status '
                'upstream:$upstream_status to:$upstream_addr '
                'origin:$http_origin';

access_log logs/error.log;


# 
server {
    listen 80; #ipv4 전체 바인딩
    listen [::]:80 default_server; #ipv6 전체 바인딩
    location / {
         return 301 https://$host$request_uri; 
         }
}



#https settings
server {
    listen       443 ssl; # https
    server_name  localhost; # 서버 이름
    ssl_certificate     "C:/Users/dorn/Desktop/programming/projects/blog/nginx/certs/localhost.pem"; # 공개키 경로
    ssl_certificate_key  "C:/Users/dorn/Desktop/programming/projects/blog/nginx/certs/localhost-key.pem"; # 개인키 경로
    ssl_protocols       TLSv1.2 TLSv1.3; # 지원하는 프로토콜
    ssl_ciphers         HIGH:!aNULL:!MD5;

    ssl_session_cache    shared:SSL:10m;
    ssl_session_timeout  10m;


    location / { # 프론트엔드 
        proxy_pass http://localhost:3000;
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For   $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        
    }   
    location /uploads/{
        alias "C:/Users/dorn/Desktop/programming/projects/files/blog/";

    }

}

}