

CREATE TABLE public.users (
	created_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NULL,
	email varchar(255) NULL,
	user_name varchar(255) NULL,
	profile_img varchar(255) NULL,
	pw varchar(255) NULL,
	refresh_token varchar(255) NULL,
	status_msg varchar(255) NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);


CREATE TABLE public.post_comment (
	created_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	post_id int8 NULL,
	author varchar(255) NULL,
	comment_text text NULL,
	CONSTRAINT post_comment_pkey PRIMARY KEY (id)
);



CREATE TABLE public.blog_posts (
	created_at timestamp(6) NULL,
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	updated_at timestamp(6) NULL,
	page_html text NULL,
	title varchar(255) NULL,
	page_json jsonb NULL,
	CONSTRAINT blog_posts_pkey PRIMARY KEY (id)
);

